# Generated by Django 5.1.2 on 2024-11-26 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comments/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
