# Generated by Django 5.1.2 on 2024-11-27 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0008_comment_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
