# Generated by Django 5.1.2 on 2024-11-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rp', '0009_remove_category_slug_remove_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
    ]
